# Disable some logs:
location = /favicon.ico { access_log off; log_not_found off; }
location = /robots.txt  { access_log off; log_not_found off; }

location = /apple-touch-icon.png { access_log off; log_not_found off; }
location = /apple-touch-icon-precomposed.png { access_log off; log_not_found off; }
location = /apple-touch-icon-120x120.png { access_log off; log_not_found off; }
location = /apple-touch-icon-120x120-precomposed.png { access_log off; log_not_found off; }
location = /apple-touch-icon-152x152.png { access_log off; log_not_found off; }
location = /apple-touch-icon-152x152-precomposed.png { access_log off; log_not_found off; }
